# Generated by Django 3.1.2 on 2020-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleID', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('damage', models.CharField(max_length=200)),
                ('seats', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
