# Generated by Django 3.1.2 on 2020-10-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20201009_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='imageurl',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
