# Generated by Django 3.1.2 on 2020-10-25 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_vehicle_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('hours', models.IntegerField()),
                ('total', models.IntegerField()),
                ('VehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.vehicle')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
