# Generated by Django 3.0.8 on 2020-10-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
