# Generated by Django 3.0.8 on 2020-10-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_vehicle_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_count',
            field=models.IntegerField(default=1),
        ),
    ]
